# Generated by Django 2.0.5 on 2018-09-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.AddField(
            model_name='dishe',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
