# Generated by Django 2.0.5 on 2018-09-11 23:59

from django.db import migrations

def seed(apps, schema_editor):
    Dishe = apps.get_model('restaurant', 'Dishe')
    Dishe( name = 'California Roll', completed=False , price= 7.00, description="sadd", image_url = "./images/californiaroll.jpg").save()
    Dishe( name = 'Spicy California Roll', completed=False , price= 8.00, description="asdds",image_url = "./images/7789_spicycaliroll.jpg").save()
    Dishe( name = 'Vegetable California Roll', completed=False , price= 7.50, description="asddsa",image_url = "./images/7714_vegecaliroll.jpg").save()
    Dishe( name = 'Spicy California Spring Roll', completed=False , price= 9.00, description="asddsa",image_url = "./images/73adc-8318_spicycalispringroll.jpg").save()
    Dishe( name = 'Rainbow Roll', completed=False , price= 8.00, description="asddsa",image_url = "./images/8219_rainroll.jpg").save()
    Dishe( name = 'Salmon Avocado Roll', completed=False , price= 6.90, description="asddsa",image_url = "./images/7673_salmavoroll.jpg").save()
    Dishe( name = 'Atlantic Salmon Avocado Roll', completed=False , price= 9.00, description="asddsa",image_url = "./images/7888_salmvolc.jpg").save()
    Dishe( name = 'Spicy Salmon Roll', completed=False , price= 7.80, description="asddsa",image_url = "./images/7739_spicysalm.jpg").save()
    Dishe( name = 'Spicy Tuna Roll', completed=False , price= 8.50, description="asddsa",image_url = "./images/7829_spicytuna.jpg").save()
    Dishe( name = 'Maple Salmon Roll', completed=False , price= 9.00, description="asddsa",image_url = "./images/8177_maplesalmroll.jpg").save()

def fallow(apps, schema_editor):
    Order = apps.get_model('restaurant', 'Order')
    Dishe = apps.get_model('restaurant', 'Dishe')
    Dishe.objects.all().delete()
    Order.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20180911_2351'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
